Repository TaloDev/backend, pull requests merged in 2025-03, with the labels that each got.

#414 Add channel management protected routes, forward API routes
  src/docs/game-channel-api.docs.ts
  src/entities/game-activity.ts
  src/entities/game-channel.ts
  src/policies/game-channel.policy.ts
  src/services/api/game-channel-api.service.ts
  src/services/game-channel.service.ts
  src/services/leaderboard.service.ts
  src/services/player.service.ts
  tests/services/_api/game-channel-api/put.test.ts
  tests/services/game-channel/delete.test.ts
  tests/services/game-channel/post.test.ts
  tests/services/game-channel/put.test.ts
  tests/services/player/index.test.ts
Labels: enhancement

#417 Fix leaving a channel with a null owner
  src/services/api/game-channel-api.service.ts
  tests/services/_api/game-channel-api/leave.test.ts
Labels: fix

#418 Release 0.63.0
  package-lock.json
  package.json
  src/docs/game-channel-api.docs.ts
  src/entities/game-activity.ts
  src/entities/game-channel.ts
  src/policies/game-channel.policy.ts
  src/services/api/game-channel-api.service.ts
  src/services/game-channel.service.ts
  src/services/leaderboard.service.ts
  src/services/player.service.ts
  tests/seed.ts
  tests/services/_api/game-channel-api/leave.test.ts
  tests/services/_api/game-channel-api/put.test.ts
  tests/services/game-channel/delete.test.ts
  tests/services/game-channel/post.test.ts
  tests/services/game-channel/put.test.ts
  tests/services/player/index.test.ts
Labels: release

#419 Increase socket rate limit from 100/10 -> 250/25
  src/socket/socketConnection.ts
Labels: enhancement

#420 Release 0.63.1
  package-lock.json
  package.json
  src/socket/socketConnection.ts
Labels: release

#422 Throw error when API_SECRET is not 32 characters long
  envs/.env.test
  src/entities/game-secret.ts
  src/services/game.service.ts
  tests/services/game/post.test.ts
Labels: enhancement

#423 Add REGISTRATION_MODE env var
  src/services/public/user-public.service.ts
  tests/services/_public/user-public/register.test.ts
Labels: enhancement

#426 Release 0.64.1
  package-lock.json
  package.json
  src/services/api-key.service.ts
  tests/seed.ts
Labels: release

#427 Fix player exports failing because of unloaded props
  src/services/data-export.service.ts
Labels: fix

#428 Game stat history API
  .eslintrc.json
  package-lock.json
  package.json
  src/docs/game-stat-api.docs.ts
  src/entities/event.ts
  src/entities/player-game-stat-snapshot.ts
  src/lib/clickhouse/clickhouse-entity.ts
  src/lib/clickhouse/formatDateTime.ts
  src/lib/dates/dateValidationSchema.ts
  src/lib/demo-data/generateDemoEvents.ts
  src/migrations/clickhouse/000CreateMigrationsTable.ts
  src/migrations/clickhouse/001CreateEventsTable.ts
  src/migrations/clickhouse/002CreateEventPropsTable.ts
  src/migrations/clickhouse/003CreateSocketEventsTable.ts
  src/migrations/clickhouse/004CreatePlayerGameStatSnapshotsTable.ts
  src/migrations/clickhouse/index.ts
  src/policies/api/game-stat-api.policy.ts
  src/services/api/event-api.service.ts
  src/services/api/game-stat-api.service.ts
  src/services/data-export.service.ts
  src/services/event.service.ts
  src/services/headline.service.ts
  src/services/player.service.ts
  src/socket/socketEvent.ts
  tests/seed.ts
  tests/services/_api/game-stat-api/history.test.ts
  tests/services/_api/game-stat-api/put.test.ts
  tests/services/_api/player-auth-api/delete.test.ts
  tests/services/_public/demo/post.test.ts
  tests/services/data-export/included-data.test.ts
  tests/services/event/get.test.ts
  tests/services/headline/get.test.ts
  tests/services/player/events.test.ts
  tests/socket/socketEvents.test.ts
  vitest.config.mts
Labels: enhancement

#429 Migrate Event timestamps to DateTime64
  src/entities/event.ts
  src/lib/demo-data/generateDemoEvents.ts
  src/migrations/clickhouse/005MigrateEventsTimestampsToDate64.ts
  src/migrations/clickhouse/index.ts
  src/services/event.service.ts
  src/services/headline.service.ts
  tests/services/_public/demo/post.test.ts
Labels: enhancement

#432 Add global stat history API
  _templates/service/new/api-service.ejs.t
  _templates/service/new/service.ejs.t
  src/docs/game-stat-api.docs.ts
  src/entities/event.ts
  src/entities/player-game-stat-snapshot.ts
  src/lib/clickhouse/clickhouse-entity.ts
  src/migrations/clickhouse/004CreatePlayerGameStatSnapshotsTable.ts
  src/policies/api/game-feedback-api.policy.ts
  src/policies/api/game-stat-api.policy.ts
  src/policies/api/leaderboard-api.policy.ts
  src/services/api/game-feedback-api.service.ts
  src/services/api/game-stat-api.service.ts
  src/services/api/leaderboard-api.service.ts
  src/services/headline.service.ts
  tests/middlewares/continuity-middleware.test.ts
  tests/services/_api/game-stat-api/globalHistory.test.ts
  tests/services/_api/game-stat-api/history.test.ts
  tests/services/_api/game-stat-api/put.test.ts
  tests/services/_api/game-stat-api/steamworksPut.test.ts
Labels: enhancement

#431 Game stat index + get APIs
  src/docs/game-stat-api.docs.ts
  src/policies/api/game-stat-api.policy.ts
  src/services/api/game-stat-api.service.ts
  tests/services/_api/game-stat-api/get.test.ts
  tests/services/_api/game-stat-api/index.test.ts
Labels: enhancement

#434 Average player stat value in global history
  src/docs/game-stat-api.docs.ts
  src/services/api/game-stat-api.service.ts
  tests/services/_api/game-stat-api/globalHistory.test.ts
Labels: enhancement

#435 Add more player value metrics in global stat history
  src/services/api/game-stat-api.service.ts
  tests/services/_api/game-stat-api/globalHistory.test.ts
Labels: enhancement
